manifest:
  remotes:
    - name: yanshay
      url-base: https://github.com/yanshay
  projects:
    - name: urob-zmk
      remote: yanshay
      path: zmk
      revision: yanshay_moergo_main_fixed
      import: app/west.yml
  self:
    path: config
